backend:
  name: github
  repo: seneffwebdev/seneff
  branch: master
media_folder: img/uploads

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "_data/home.yml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Title, name: title, widget: string }
          - { label: "Linked In URL", name: linkedin, widget: string, required: false}
          - { label: "Facebook URL", name: facebook, widget: string, required: false }
          - { label: "Twitter URL", name: twitter, widget: string, required: false }
          - { label: Description, name: description, widget: markdown }
          - { label: "CV Download URL", name: cvdownload, widget: string }
