backend:
  name: github
  repo: seneffwebdev/seneff
  branch: master
media_folder: img/uploads

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "_data/home.yml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Title, name: title, widget: string }
          - {
              label: "Linked In URL",
              name: linkedin,
              widget: string,
              required: false,
            }
          - {
              label: "Facebook URL",
              name: facebook,
              widget: string,
              required: false,
            }
          - {
              label: "Twitter URL",
              name: twitter,
              widget: string,
              required: false,
            }
          - { label: Description, name: description, widget: markdown }
          - { label: "CV Download URL", name: cvdownload, widget: string }
          - { label: Email, name: email, widget: string, required: false }
          - { label: Skype, name: skype, widget: string, required: false }
          - { label: Phone, name: phone, widget: string, required: false }
          - { label: Address, name: address, widget: markdown, required: false }
          - {
              label: "Education Picture (265x265 only)",
              name: educationPicture,
              widget: image,
              default: "/img/uploads/default.png",
            }
          - {
              label: "Featured Article Title (set value to the - (minus) character to disable)",
              name: featuredArticle,
              widget: string,
              required: false,
            }
          - {
              label: "Featured Article Subtitle",
              name: featuredArticleSubtitle,
              widget: string,
              required: false,
            }
          - {
              label: "Featured Article Description",
              name: featuredArticleDescription,
              widget: string,
              required: false,
            }
          - {
              label: "Featured Article Link",
              name: featuredArticleLink,
              widget: string,
              required: false,
            }
          - {
              label: "Featured Article Image",
              name: featuredArticleImage,
              widget: image,
              required: false,
            }
  - label: "Education"
    name: "education"
    folder: "_education"
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}"
    fields: # The fields each document in this collection have
      - {
          label: "Years (2001-2002 for example)",
          name: "year",
          widget: "string",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
  - label: "Research"
    name: "research"
    folder: "_research"
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}"
    fields: # The fields each document in this collection have
      - { label: "title", name: "title", widget: "string" }
      - { label: "Description Short", name: "description", widget: "string" }
      - {
          label: "Icon",
          name: "icon",
          widget: "select",
          options:
            ["molecule", "test-tube-alt", "earth", "sand-clock", "brain"],
        }
      - {
          label: "Description Long",
          name: "descriptionLong",
          widget: "markdown",
        }
      - { label: "Priority", name: "priority", widget: "number" }
  - label: "Publications"
    name: "publications"
    folder: "_publications"
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}"
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Image (195x195 only)", name: "image", widget: "image" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Priority", name: "priority", widget: "number" }
  - label: "Teaching"
    name: "teaching"
    folder: "_teaching"
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}"
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - {
          label: "Tab",
          name: "tab",
          widget: "select",
          options:
            ["Interviews and Webinars", "Podcast", "Video and Audio Clips"],
        }
      - { label: "Priority", name: "priority", widget: "number" }
